INSERT INTO RACE(RACE_DAY, RACE_NUMBER, RACE_NAME) VALUES ('2023-05-23', 1, 'Race 1');

INSERT INTO RUNNER(RUNNER_NUMBER, RUNNER_RACE_DAY, RUNNER_RACE_NUMBER, RUNNER_NAME) VALUES (1, '2023-05-23', 1, 'Runner 1');
INSERT INTO RUNNER(RUNNER_NUMBER, RUNNER_RACE_DAY, RUNNER_RACE_NUMBER, RUNNER_NAME) VALUES (2, '2023-05-23', 1, 'Runner 2');
INSERT INTO RUNNER(RUNNER_NUMBER, RUNNER_RACE_DAY, RUNNER_RACE_NUMBER, RUNNER_NAME) VALUES (3, '2023-05-23', 1, 'Runner 3');
INSERT INTO RUNNER(RUNNER_NUMBER, RUNNER_RACE_DAY, RUNNER_RACE_NUMBER, RUNNER_NAME) VALUES (4, '2023-05-23', 1, 'Runner 4');
INSERT INTO RUNNER(RUNNER_NUMBER, RUNNER_RACE_DAY, RUNNER_RACE_NUMBER, RUNNER_NAME) VALUES (5, '2023-05-23', 1, 'Runner 5');
INSERT INTO RUNNER(RUNNER_NUMBER, RUNNER_RACE_DAY, RUNNER_RACE_NUMBER, RUNNER_NAME) VALUES (6, '2023-05-23', 1, 'Runner 6');