CREATE TABLE IF NOT EXISTS RACE(
    RACE_DAY DATE NOT NULL,
    RACE_NUMBER INT NOT NULL,
    RACE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY
    (
        RACE_DAY ASC,
        RACE_NUMBER ASC
    )
);

CREATE TABLE IF NOT EXISTS RUNNER(
    RUNNER_NUMBER INT NOT NULL,
    RUNNER_RACE_DAY DATE NOT NULL,
    RUNNER_RACE_NUMBER INT NOT NULL,
    RUNNER_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY
    (
        RUNNER_NUMBER ASC,
        RUNNER_RACE_DAY ASC,
        RUNNER_RACE_NUMBER ASC
    )
);